name: Gitleaks Checks

on:
  pull_request:
    branches:
      - '*'

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.x' # Use the desired Go version

    - name: Install Gitleaks
      run: go get github.com/zricethezav/gitleaks/v7

    - name: Run Gitleaks
      run: |
        gitleaks --path . --verbose --redact
