name: Gitleaks Checks

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install GitLeaks
      run: |
        git clone https://github.com/gitleaks/gitleaks.git
        cd gitleaks
        make build
      shell: bash

    - name: Run GitLeaks
      id: gitleaks
      run: |
        gitleaks detect -f csv
      continue-on-error: true
